//
//  RootViewController.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootDisplayLogic: class
{
    func displaySomething(viewModel: Root.Something.ViewModel)
}

class RootViewController: UIViewController, RootDisplayLogic
{
    // MARK: Destination ViewController
    static fileprivate var rootViewController: RootViewController?
    
    static func sharedInstance() -> RootViewController {
        if let sharedInstance = RootViewController.rootViewController {
            
            return sharedInstance
        }else{
            RootViewController.rootViewController = RootViewController()
            _ = RootViewController.rootViewController?.view
            if let rootController = RootViewController.rootViewController{
                return rootController
            }else{
                return RootViewController()
            }
            
        }
    }
    // MARK: interactor, router
    var interactor: RootBusinessLogic?
    var router: (NSObjectProtocol & RootRoutingLogic & RootDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = RootInteractor()
        let presenter = RootPresenter()
        let router = RootRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Root.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Root.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
