//
//  RootRouter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


@objc protocol RootRoutingLogic
{
//    func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToHomeMenu()
    func routeToNewsMenu()
    func routeToActivityMenu()
    func routeToSettingMenu()
}

protocol RootDataPassing
{
    var dataStore: RootDataStore? { get }
}

class RootRouter: NSObject, RootRoutingLogic, RootDataPassing
{
    weak var viewController: RootViewController?
    var dataStore: RootDataStore?
    
    // MARK: Routing
    
    func routeToHomeMenu(){
        AppDirector.showHome()
    }
    func routeToNewsMenu(){
        AppDirector.showNews()
    }
    func routeToActivityMenu(){
        AppDirector.showActivity()
    }
    func routeToSettingMenu(){
        AppDirector.showSetting()
    }
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: RootViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: RootDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
