//
//  RootInteractor.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootBusinessLogic
{
  func doSomething(request: Root.Something.Request)
}

protocol RootDataStore
{
  //var name: String { get set }
}

class RootInteractor: RootBusinessLogic, RootDataStore
{
  var presenter: RootPresentationLogic?
  var worker: RootWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Root.Something.Request)
  {
    worker = RootWorker()
    worker?.doSomeWork()
    
    let response = Root.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
