//
//  DetailNewsViewController.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 22/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit

protocol DetailNewsDisplayLogic: AnyObject
{
    func displayWebView(viewModel: DetailNews.ShowWebDetail.ViewModel)
}

class DetailNewsViewController: UIViewController, DetailNewsDisplayLogic
{
    // MARK: Destination ViewController
    class func instantiateFromStoryboard() -> DetailNewsViewController {
        let storyboard = UIStoryboard(name: "News", bundle: nil)
        return storyboard.instantiateViewController(withIdentifier: String(describing: self)) as! DetailNewsViewController
    }
    // MARK: interactor, router
    var interactor: DetailNewsBusinessLogic?
    var router: (NSObjectProtocol & DetailNewsRoutingLogic & DetailNewsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = DetailNewsInteractor()
        let presenter = DetailNewsPresenter()
        let router = DetailNewsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    func prepareRoutingFromNews(source: NewsDataStore){
        let interactor = DetailNewsInteractor()
        interactor.article = source.article
        
        openDetailNews()
    }
    
//    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
//    {
//        if let scene = segue.identifier {
//            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
//            if let router = router, router.responds(to: selector) {
//                router.perform(selector, with: segue)
//            }
//        }
//    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
    }
    
    // MARK: Button Action
    @IBAction func back_click(_ sender: Any) {
        self.navigationController?.popViewController(animated: true)
    }
    
    // MARK: Show Detail News WebView
    
    @IBOutlet weak var webView: WKWebView!
    
    func openDetailNews()
    {
        let request = DetailNews.ShowWebDetail.Request()
        interactor?.showDetailWebView(request: request)
    }
    
    func displayWebView(viewModel: DetailNews.ShowWebDetail.ViewModel)
    {
        
        if let url = URL(string: viewModel.urlWebView){
            webView.load(URLRequest(url: url))
        }
        
    }
}
