//
//  HomeInteractor.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func checkIsUserLogin(request: Home.UserLogin.Request)
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
    
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var profile: Profile = Profile()
    
    // MARK: Do something
    func checkIsUserLogin(request: Home.UserLogin.Request) {
        worker = HomeWorker()
        worker?.doSomeWork()
        
        let response = Home.UserLogin.Response(profile: profile)
        if response.profile.email.isEmpty{
            presenter?.presentShowLogin()
        }else{
            presenter?.presentUpdateProfileAccessToken(response: response)
        }
        
    }
}
