//
//  HomePresenter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentUpdateProfileAccessToken(response: Home.UserLogin.Response)
    func presentShowLogin()
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentUpdateProfileAccessToken(response: Home.UserLogin.Response)
    {
        let profile = response.profile
        let viewModel = Home.UserLogin.ViewModel(displayProfile: Home.UserLogin.ViewModel.DisplayProfileUser(phone: profile.phone, email: profile.email))
        viewController?.displayUpdateProfileAccessToken(viewModel: viewModel)
    }
    
    func presentShowLogin(){
        viewController?.displayLogin()
    }
}
