//
//  NewsInteractor.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsBusinessLogic
{
  func doSomething(request: News.Something.Request)
}

protocol NewsDataStore
{
  //var name: String { get set }
}

class NewsInteractor: NewsBusinessLogic, NewsDataStore
{
  var presenter: NewsPresentationLogic?
  var worker: NewsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: News.Something.Request)
  {
    worker = NewsWorker()
    worker?.doSomeWork()
    
    let response = News.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
