//
//  NewsPresenter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsPresentationLogic
{
  func presentSomething(response: News.Something.Response)
}

class NewsPresenter: NewsPresentationLogic
{
  weak var viewController: NewsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: News.Something.Response)
  {
    let viewModel = News.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
