//
//  ActivityInteractor.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ActivityBusinessLogic
{
  func doSomething(request: Activity.Something.Request)
}

protocol ActivityDataStore
{
  //var name: String { get set }
}

class ActivityInteractor: ActivityBusinessLogic, ActivityDataStore
{
  var presenter: ActivityPresentationLogic?
  var worker: ActivityWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Activity.Something.Request)
  {
    worker = ActivityWorker()
    worker?.doSomeWork()
    
    let response = Activity.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
