//
//  NewsPresenter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsPresentationLogic
{
    func presentArticleNews(response: News.GetNews.Response)
    func presentNewsDetail(response: News.SelectNews.Response)
}

class NewsPresenter: NewsPresentationLogic
{
    weak var viewController: NewsDisplayLogic?
    
    // MARK: Do something
    
    func presentArticleNews(response: News.GetNews.Response)
    {
        let viewModel = News.GetNews.ViewModel(displayedNewsList: response.articles)
        viewController?.displayArtileNews(viewModel: viewModel)
    }
    
    func presentNewsDetail(response: News.SelectNews.Response){
        let viewModel = News.SelectNews.ViewModel(article: response.article)
        viewController?.displayNewsDetail(viewModel: viewModel)
    }
}
