//
//  NewsRouter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsRoutingLogic
{
    func routeToDetailNews()
}

protocol NewsDataPassing
{
  var dataStore: NewsDataStore? { get }
}

class NewsRouter: NSObject, NewsRoutingLogic, NewsDataPassing
{
  weak var viewController: NewsViewController?
  var dataStore: NewsDataStore?
  
  // MARK: Routing
  
    func routeToDetailNews(){
        AppDirector.showDetailNewsViewController(source: dataStore!)
    }

  // MARK: Navigation
  
//  func navigateToSomewhere(source: NewsViewController, destination: SomewhereViewController)
//  {
//    source.show(destination, sender: nil)
//  }
  
  // MARK: Passing data
  
//  func passDataToDetailNews(source: NewsDataStore, destination: inout DetailNewsDataStore)
//  {
//    destination.article = source.article
//  }
}
