//
//  LoginPresenter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSomething(response: Login.LoginSubmit.Response)
    func presentSubmitLogin(response: Login.LoginSubmit.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Login.LoginSubmit.Response)
    {
        let viewModel = Login.LoginSubmit.ViewModel(accessToken: "")
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentSubmitLogin(response: Login.LoginSubmit.Response){
        let viewModel = Login.LoginSubmit.ViewModel(accessToken: "AssumeThisTextIsAccessToken")
        viewController?.displayHome(viewModel: viewModel)
    }
}
