//
//  LoginModels.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum LoginSubmit
  {
    struct Request
    {
        let username:String
        let password:String
    }
    struct Response
    {
        let success:Bool
        let username:String = ""
        let password:String = ""
    }
    struct ViewModel
    {
        let accessToken:String
    }
  }
}
