//
//  ActivityPresenter.swift
//  CleanAppPracetice02
//
//  Created by Papon Supamongkonchai on 20/7/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ActivityPresentationLogic
{
  func presentSomething(response: Activity.Something.Response)
}

class ActivityPresenter: ActivityPresentationLogic
{
  weak var viewController: ActivityDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Activity.Something.Response)
  {
    let viewModel = Activity.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
